### ISSUE TITLE
TypeError : S is not iterable

### ISSUE THREAD

**Issue by karthikchiru12** [yakshavingdevs/datadance#38]
There is an issue while using playground.

### How to reproduce
```yaml
_$divisibleByThree:
  dbythree : derived.item % 3 == 0
  
output : input.lastEx | forEach({},_$divisibleByThree)
```
Merge method : Coming in all merge methods.

Input used : 

```json
{
    "name": {
        "first": " malory",
        "last": "archer"
    },
    "exes": [
        " Nikolai Jakov ",
        "Len Trexler",
        "Burt Reynolds"
    ],
    "lastEx": [
      3
      ]
}
```
