### ISSUE TITLE
The immutability of the input is not maintained within the forEach loop

### ISSUE THREAD

**Issue by karthikchiru12** [yakshavingdevs/datadance#46]
- Problem
```yaml
x : _|range(0,5,1)

_$greatherThan2 :
  item : derived.item
  result : derived.item > 2
  sum : derived.result ? derived.sum + derived.item : derived.sum
  sum_original : input.sum
y : derived.x | forEach(derived._$greatherThan2,{sum : 0},'result') 

```

- And the output we are currently getting : 
```json
"y": [
    {
      "item": 3,
      "result": true,
      "sum": 3,
      "sum_original": 0
    },
    {
      "item": 4,
      "result": true,
      "sum": 7,
      "sum_original": 3
    },
    {
      "item": 5,
      "result": true,
      "sum": 12,
      "sum_original": 7
    }
  ]

```
- But the expected value for the sum_original should be always 0,but its not.
